# Auto-generated by setup-toolchain.ps1 — dot-source to re-activate the build env in a new shell:
#   . .\activate-env.ps1
$env:JAVA_HOME = 'C:\Users\User\AppData\Local\MyGameToolchain\jdk-17.0.19+10'
$env:ANDROID_SDK_ROOT = 'C:\Users\User\AppData\Local\MyGameToolchain\android-sdk'
$env:ANDROID_HOME = 'C:\Users\User\AppData\Local\MyGameToolchain\android-sdk'
$env:PATH = 'C:\Users\User\AppData\Local\MyGameToolchain\node-v20.20.2-win-x64;C:\Users\User\AppData\Local\MyGameToolchain\jdk-17.0.19+10\bin;C:\Users\User\AppData\Local\MyGameToolchain\android-sdk\cmdline-tools\latest\bin;C:\Users\User\AppData\Local\MyGameToolchain\android-sdk\platform-tools;' + $env:PATH
Write-Host 'Build env activated (Node/JDK/Android SDK on PATH).' -ForegroundColor Green
