<#
Portable Android build toolchain setup (no admin rights, no installers).
Downloads + extracts Node LTS, Temurin JDK 17, and Android command-line tools into a
no-space folder under %LOCALAPPDATA%, then installs the SDK packages Capacitor needs
and accepts the licenses.

DOT-SOURCE this so the env vars persist in your shell:
    . .\setup-toolchain.ps1

Re-running is safe: downloads/extractions already present are skipped.
#>

$ErrorActionPreference = 'Stop'
$base = Join-Path $env:LOCALAPPDATA 'MyGameToolchain'
New-Item -ItemType Directory -Force -Path $base | Out-Null
$dl = Join-Path $base 'downloads'
New-Item -ItemType Directory -Force -Path $dl | Out-Null

# Use TLS 1.2 for older download endpoints
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

function Get-File($url, $outFile) {
    if (Test-Path $outFile) { Write-Host "  cached: $(Split-Path $outFile -Leaf)" -ForegroundColor DarkGray; return }
    Write-Host "  downloading: $url" -ForegroundColor Cyan
    Invoke-WebRequest -Uri $url -OutFile $outFile -UseBasicParsing
}

# ---------------------------------------------------------------- Node.js (LTS, v20)
Write-Host "[1/3] Node.js (portable)" -ForegroundColor Yellow
$nodeDir = Get-ChildItem -Path $base -Directory -Filter 'node-v20*' -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $nodeDir) {
    $index = Invoke-RestMethod -Uri 'https://nodejs.org/dist/index.json' -UseBasicParsing
    $ver = ($index | Where-Object { $_.lts -and $_.version -like 'v20.*' } | Select-Object -First 1).version
    $nodeZip = Join-Path $dl "node-$ver-win-x64.zip"
    Get-File "https://nodejs.org/dist/$ver/node-$ver-win-x64.zip" $nodeZip
    Write-Host "  extracting Node $ver ..." -ForegroundColor DarkGray
    Expand-Archive -Path $nodeZip -DestinationPath $base -Force
    $nodeDir = Get-ChildItem -Path $base -Directory -Filter 'node-v20*' | Select-Object -First 1
}
$nodeHome = $nodeDir.FullName
Write-Host "  Node: $nodeHome" -ForegroundColor Green

# ---------------------------------------------------------------- JDK 17 (Temurin)
Write-Host "[2/3] JDK 17 (portable Temurin)" -ForegroundColor Yellow
$jdkDir = Get-ChildItem -Path $base -Directory -Filter 'jdk-17*' -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $jdkDir) {
    $jdkZip = Join-Path $dl 'temurin-jdk17.zip'
    Get-File 'https://api.adoptium.net/v3/binary/latest/17/ga/windows/x64/jdk/hotspot/normal/eclipse?project=jdk' $jdkZip
    Write-Host "  extracting JDK ..." -ForegroundColor DarkGray
    Expand-Archive -Path $jdkZip -DestinationPath $base -Force
    $jdkDir = Get-ChildItem -Path $base -Directory -Filter 'jdk-17*' | Select-Object -First 1
}
$javaHome = $jdkDir.FullName
Write-Host "  JDK: $javaHome" -ForegroundColor Green

# ---------------------------------------------------------------- Android cmdline-tools + SDK
Write-Host "[3/3] Android SDK (command-line tools)" -ForegroundColor Yellow
$sdkRoot = Join-Path $base 'android-sdk'
$cmdlineLatest = Join-Path $sdkRoot 'cmdline-tools\latest'
if (-not (Test-Path (Join-Path $cmdlineLatest 'bin\sdkmanager.bat'))) {
    $cltZip = Join-Path $dl 'android-cmdline-tools.zip'
    Get-File 'https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip' $cltZip
    Write-Host "  extracting command-line tools ..." -ForegroundColor DarkGray
    $tmp = Join-Path $base '_clt_tmp'
    if (Test-Path $tmp) { Remove-Item $tmp -Recurse -Force }
    Expand-Archive -Path $cltZip -DestinationPath $tmp -Force
    New-Item -ItemType Directory -Force -Path $cmdlineLatest | Out-Null
    # zip contains a top-level 'cmdline-tools' folder; move its contents into latest/
    Get-ChildItem (Join-Path $tmp 'cmdline-tools') | Move-Item -Destination $cmdlineLatest -Force
    Remove-Item $tmp -Recurse -Force
}
Write-Host "  Android SDK root: $sdkRoot" -ForegroundColor Green

# ---------------------------------------------------------------- Activate env (persists when dot-sourced)
$env:JAVA_HOME = $javaHome
$env:ANDROID_SDK_ROOT = $sdkRoot
$env:ANDROID_HOME = $sdkRoot
$env:PATH = "$nodeHome;$javaHome\bin;$cmdlineLatest\bin;$sdkRoot\platform-tools;$env:PATH"

# ---------------------------------------------------------------- Install SDK packages + licenses
$sdkmanager = Join-Path $cmdlineLatest 'bin\sdkmanager.bat'
Write-Host "Accepting SDK licenses ..." -ForegroundColor Yellow
$yes = ("y`r`n" * 60)
$yes | & $sdkmanager --sdk_root="$sdkRoot" --licenses | Out-Null
Write-Host "Installing SDK packages (platform-tools, platform 34, build-tools 34) ..." -ForegroundColor Yellow
& $sdkmanager --sdk_root="$sdkRoot" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

# ---------------------------------------------------------------- Write a reusable activate script
$activate = Join-Path $PSScriptRoot 'activate-env.ps1'
@"
# Auto-generated by setup-toolchain.ps1 — dot-source to re-activate the build env in a new shell:
#   . .\activate-env.ps1
`$env:JAVA_HOME = '$javaHome'
`$env:ANDROID_SDK_ROOT = '$sdkRoot'
`$env:ANDROID_HOME = '$sdkRoot'
`$env:PATH = '$nodeHome;$javaHome\bin;$cmdlineLatest\bin;$sdkRoot\platform-tools;' + `$env:PATH
Write-Host 'Build env activated (Node/JDK/Android SDK on PATH).' -ForegroundColor Green
"@ | Set-Content -Path $activate -Encoding UTF8

Write-Host ""
Write-Host "Toolchain ready." -ForegroundColor Green
Write-Host ("  node : " + (node --version)) -ForegroundColor Green
Write-Host ("  java : " + ((java -version 2>&1)[0])) -ForegroundColor Green
Write-Host "Re-activate later in a new terminal with:  . .\activate-env.ps1" -ForegroundColor Cyan
